# Generated by Django 2.2.28 on 2025-02-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250213_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='unknown-slug', unique=True),
            preserve_default=False,
        ),
    ]
